---
# https://github.com/pygobject/pygobject-travis-ci-docker-examples/blob/master/.travis.yml
notifications:
  email:
    on_success: never
    on_failure: change

sudo: required
services: docker
language: python
python:
    - "3.6"
env:

  - DOCKER_TAG="python2" PYTHON="python" PIP="pip2"
  - DOCKER_TAG="python3" PYTHON="python3" PIP="pip3"

before_install:
  # Create a docker image called "myimage"
  # - docker build -t myimage -f "$DOCKER_FILE" .
  - pip install coveralls
  - docker pull wizardsoftheweb/py-rofi-bus-images:"$DOCKER_TAG"

before_script:
  # create a docker container from the image, mount the current working
  # directory to /app inside the container and let the container running
  # in the background. The resulting container ID will be saved to
  # container_id so we can reference it later on.
  - docker run --volume "$(pwd):/app" --workdir "/app" --tty --detach wizardsoftheweb/py-rofi-bus-images:"$DOCKER_TAG" bash > container_id

script:
  # run our tests in the running contained
  - docker exec "$(cat container_id)" dnf update -y "$PYTHON"-setuptools
  - docker exec "$(cat container_id)" "$PIP" install -U setuptools
  - docker exec "$(cat container_id)" mkdir -p /usr/local/lib/python3.6/site-packages/
  - docker exec "$(cat container_id)" "$PYTHON" setup.py install
  - docker exec "$(cat container_id)" xvfb-run -a "$PYTHON" setup.py test

after_script:
  # stop the container
  - sudo chown -R $(whoami) .
  - ls -alh $PWD
  - cat .coverage
  - sed -i "s,/app/,${PWD}/,g" .coverage
  - coveralls
  - docker exec -e TRAVIS="$TRAVIS" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" "$(cat container_id)" coveralls
  - docker stop "$(cat container_id)"
