---
# https://github.com/pygobject/pygobject-travis-ci-docker-examples/blob/master/.travis.yml
notifications:
  email:
    on_success: never
    on_failure: change

sudo: required
services: docker
language: generic
env:

  - DOCKER_FILE="Dockerfile.fedora-28.py2" PYTHON="python"
  - DOCKER_FILE="Dockerfile.fedora-28.py3" PYTHON="python3"

before_install:
  # Create a docker image called "myimage"
  - docker build -t myimage -f "$DOCKER_FILE" .

before_script:
  # create a docker container from the image, mount the current working
  # directory to /app inside the container and let the container running
  # in the background. The resulting container ID will be saved to
  # container_id so we can reference it later on.
  - docker run --volume "$(pwd):/app" --workdir "/app" --tty --detach myimage bash > container_id

script:
  # run our tests in the running contained
  - docker exec "$(cat container_id)" mkdir -p $("$PYTHON" -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())')
  - docker exec "$(cat container_id)" "$PYTHON" setup.py install
  - docker exec "$(cat container_id)" xvfb-run -a "$PYTHON" setup.py test

after_script:
  # stop the container
  - docker exec "$(cat container_id)" coveralls
  - docker stop "$(cat container_id)"
