---
notifications:
  email:
    on_success: never
    on_failure: change

cache: pip

sudo: true

language: python
python:
  - '2.7'
  - '3.6'

install:
  - sudo apt install libgirepository1.0-dev
  - python setup.py install

script:
  - python setup.py test
